server:
  servlet:
    context-path: /ims
  port: 8080
  max-http-header-size: 10000000
  
debezium:
  config:
    database.hostname: imscloud.crwhumq5w81a.eu-central-1.rds.amazonaws.com
    database.port: 5432
    database.user: imscloud
    database.password: imscloud
    database.dbname: ims
    schema.whitelist: ims_schema
    table.whitelist: ims_schema.snapshot_decimal_data,ims_schema.range_decimal_data,ims_schema.analytics_engine_template,ims_schema.analytics_profile
    heartbeat.interval.ms: 600000
    heartbeat.action.query: UPDATE ims_schema.debezium_heartbeat set last_heartbeat_ts = now()
    database.server.name: ims_dbz
    name: dbzEmbeddedEngine 
    plugin.name: pgoutput
    connector.class: io.debezium.connector.postgresql.PostgresConnector
    offset.storage: org.apache.kafka.connect.storage.FileOffsetBackingStore
    offset.storage.file.filename: tmp/cdc-offset.dat
    offset.flush.interval.ms: 60000
    publication.autocreate.mode: filtered
    tombstones.on.delete: false
    key.converter.schemas.enable: false
    value.converter.schemas.enable: false
      
spring:
  datasource:
    url: jdbc:postgresql://imscloud.crwhumq5w81a.eu-central-1.rds.amazonaws.com/ims?currentSchema=ims_schema&reWriteBatchedInserts=true
    username: imscloud
    password: imscloud
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQL95Dialect
      hibernate.default_schema: ims_schema
      hibernate.jdbc.time_zone: UTC
      hibernate.jdbc.batch_size: 100
      hibernate.jdbc.batch_versioned_data: true
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.show-sql: false
      hibernate.generate_statistics: false
  liquibase:
    enabled: true
    change-log: classpath:/changelog/changelog_master.xml
    default-schema: ims_schema
    contexts: libya
    drop-first: false
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB      
logging:
  level:
    ROOT: WARN
    io.debezium: INFO
    com.oak.service: DEBUG
    com.oak.cdc: DEBUG
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    org.hibernate.engine.internal.StatisticalLoggingSessionEventListener: OFF
    org.hibernate.stat: OFF